config/routes.rb
Team10MiniProject::Application.routes.draw do

  root 'calendars#index'
  get "pages/awaiting", as: :awaiting
  get "pages/welcome", as: :welcome

  resources :boards  do
    resources :conversations do
      get :ajax_get_comments
      resources :comments
    end
  end

  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users do 
    member do
      get :report
    end
  end

  resources :shows

  resources :calendars

  resources :show_dates do
    member do
      get :show_foh
    end
    resources :fohs, only: [:new, :create]
  end

  resources :fohs, only: [:index]

  resources :trainings do
    member do
      get :attend
      get :attendee
    end
    collection do
      put :record_attendance

    end
    end

  resources :workshops do
    member do
      get :attend
      get :attendee
    end
    collection do
      put :record_attendance
    end
  end

  resources :show_roles do
    resources :role_applications, only: [:new, :create, :show]
  end
  resources :role_applications

  resources :socials


end

app/models/training.rb
class Training < ActiveRecord::Base
  validates :title, :category, :description, :date, :duration, :time, presence: true
  validate :date_cannot_be_in_the_past
  validate :time_cannot_be_in_the_past
  validates :duration, numericality: {greater_than: 0, less_than_or_equal_to: 600}


  has_many :training_records, dependent: :destroy


end

app/controllers/trainings_controller.rb
#
# trainings_controller.rb
#
# This is the controller class for Training events. Different users have different permissions to view, create, update, and delete a training event.
# Users can also attend and have their attendance record marked
#
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy, :attendee]
  before_filter :set_nav_identifier
  load_and_authorize_resource

  # GET /trainings
  def index
    @trainings = Training.all
  end

  # GET /trainings/1
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  def create
    @training = Training.new(training_params)

    if @training.save
      redirect_to @training, notice: 'Training was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /trainings/1
  def update
    if @training.update(training_params)
      redirect_to @training, notice: 'Training was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /trainings/1
  def destroy
    @training.destroy
    redirect_to trainings_url, notice: 'Training was successfully destroyed.'
  end

  # Custom method to register to attend a training session
  def attend
    user_id = current_user.id
    training_id = params[:id]
    TrainingRecord.create_new_record user_id, training_id
    redirect_to @training, notice: "You have successfully registered for #{@training.title}"
  end

  # Displays attendance records of a workshop
  def attendee
    @training_records = @training.training_records
  end

  # Custom method to mark the attendance record of a training event
  def record_attendance
    TrainingRecord.where(id: params[:unattended_ids]).update_all(attended: true)
    redirect_to trainings_url, notice: "The attendance was successfully updated"
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_training
    @training = Training.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def training_params
    params.require(:training).permit(:title, :category, :description, :date, :time, :duration)
  end

  def set_nav_identifier
    @current_nav_identifier = :events
  end

end

app/helpers/trainings_helper.rb
#
# trainings_helper.rb
#
# This is an helper class for Training.
# It contains a method for displaying navigation links based on the current logged in user.
# It also provides custom display methods for training and can check a current user's attendance for an event
#
module TrainingsHelper
  # This method is implemented to display the training name and three different icons for view, edit and delete buttons.
  def training_name_links(training)
    content_tag :h3 do
    if ((current_user.role? "SeniorCommittee") || (current_user.role? "TechManager"))
      [
        link_to_button('buttonshowname',training.title,training),
        link_to_button('buttonedit','Edit', edit_training_path(training)),
        link_to_button('buttondelete','Delete', training, {
          data: {confirm: 'Are you sure?'},
          method: :delete
      })
      ].join(' ').html_safe
    else
      [ link_to(training.title,training)
      ].join(' ').html_safe
    end
    end
  end

  # This method checks if a user can attend or has registered to attend a training
  def check_training_attendee(training)
    if(TrainingRecord.training_applied current_user.id, training.id).empty?
       link_to "Attend Training", attend_training_path if training.date >= Date.today
    else
      "You have registered for #{training.title}"
    end
  end

  # control the navigation links for different roles of users
  def training_navigation_links(training)
    content_tag :h3 do
      if ((current_user.role? "SeniorCommittee") || (current_user.role? "TechManager"))
        [
            link_to('<i class="icon-circle-arrow-left"></i> Back'.html_safe,trainings_path),
            "|",
            link_to('<i class="icon-edit-sign"></i> Edit'.html_safe,edit_training_path(training))  ,
            "|"                                                        ,
            link_to('<i class="icon-trash"></i> Delete'.html_safe,training, :method => :delete, :data => { :confirm => 'Are you sure?'})
        ].join(' ').html_safe
      else
        [link_to('<i class="icon-circle-arrow-left"></i> Back'.html_safe,trainings_path)].join(' ').html_safe
      end
    end
  end

 end

app/views/trainings/_form.html.haml
//display errors (if any))
= simple_form_for(@training) do |f|
  = f.error_notification

  //display form to fill in required inputs
  .form-inputs
    = f.input :title
    = f.input :category
    = f.input :description
    %br= f.label :date
    = f.text_field :date, as: :bootstrap_datepicker
    %br= f.label :time
    = f.text_field :time, :value => (@training.time ? @training.time.strftime("%I:%M%p") : ''), as: :bootstrap_timepicker
    = f.input :duration, :label => "Duration (in minutes)"
    %br

  .form-actions
    = f.button :submit

app/views/trainings/attendee.html.haml
// Displays registered users for a training event and a means to record those who attended
.page-header
  %h1 Registered Users for #{@training.title}

-if @training_records.empty?
  .jumbotron
    %h2 No user has registered for this training yet
  %h3=link_to('<i class="icon-circle-arrow-left"></i> Back'.html_safe,@training)

-else
  = form_tag record_attendance_trainings_path, :method =>:put do
    %table.table.table-striped.table-responsive.table-nonfluid.table-customstyle
      %thead
        %tr
          %th First Name
          %th Last Name
          %th Email
          %th Attended?

      %tbody
        - @training_records.each do |record|
          %tr
            %td= link_to "#{record.user.firstname}", user_path(record.user)
            %td= record.user.lastname
            %td= record.user.email
            -if record.attended
              %td attended
            -else
              %td= check_box_tag "unattended_ids[]", record.id,false
    %h3=submit_tag "Submit Attendance"
    %br
    %br
    %h3=link_to('<i class="icon-circle-arrow-left"></i> Back'.html_safe,@training)
%br

app/views/trainings/edit.html.haml
%h1 Editing training
.div.tiles
  = render 'form'
.div.tiles
  %p
    %br
    %br
  = link_to 'Show', @training
  \|
  = link_to 'Back', trainings_path

app/views/trainings/index.html.haml
//Displays a list of all training events
.page-header
  %h1 List of trainings

.dashboard.clearfix
  %ul.tiles
    - if ((current_user.role? "SeniorCommittee") || (current_user.role? "TechManager"))
      %a.buttonnewtraining{href:new_training_path, role:"button"} Create New Training
      %br

    - @trainings.each do |training|
      = training_name_links(training) # displays the training name as well as related icons
      .tile.tile-big.tile-12{"data-page-name" => "random-r-page", "data-page-type" => "r-page"}
        .col1.clearfix
          %i.icon-tasks
          #{training.title}
        .col2.clearfix
          %div
            %p
              = training.description

        %figure
          %figcaption.tile-caption.caption-right 
            Type: #{training.category}
            %br
            Date: #{training.date.strftime("%B %d, %Y")}
            %br
            Time: #{training.time.strftime("%I:%M%p")}
            %br
            Duration: #{training.duration} mins

app/views/trainings/new.html.haml
%h1 New training

= render 'form'
%br
%br
= link_to 'Back', trainings_path

app/views/trainings/show.html.haml
%p
  %h2= @training.title
%p
  %b Type:
  = @training.category
%p
  %b Description:
  = @training.description
%p
  %b Date:
  = @training.date.strftime("%B %d, %Y")
%p
  %b Time:
  = @training.time.strftime("%I:%M%p")
%p
  %b Duration:
  #{@training.duration} minutes

%h4=check_training_attendee(@training)
%p
- if (current_user.role? "TechManager")
  %a.btn.btn-primary.btn-lg{href:attendee_training_path(@training) , role: "button"} View registered users

=training_navigation_links(@training)