config/routes.rb
Team10MiniProject::Application.routes.draw do

  root 'calendars#index'
  get "pages/awaiting", as: :awaiting
  get "pages/welcome", as: :welcome

  resources :boards  do
    resources :conversations do
      get :ajax_get_comments
      resources :comments
    end
  end

  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users do 
    member do
      get :report
    end
  end

  resources :shows

  resources :calendars

  resources :show_dates do
    member do
      get :show_foh
    end
    resources :fohs, only: [:new, :create]
  end

  resources :fohs, only: [:index]

  resources :trainings do
    member do
      get :attend
      get :attendee
    end
    collection do
      put :record_attendance

    end
    end

  resources :workshops do
    member do
      get :attend
      get :attendee
    end
    collection do
      put :record_attendance
    end
  end

  resources :show_roles do
    resources :role_applications, only: [:new, :create, :show]
  end
  resources :role_applications

  resources :socials


end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  belongs_to :user
  belongs_to :board
  validates :title, :body, presence: true
end

app/controllers/conversations_controller.rb
#
#      conversations_controller.rb
#
# This is the controller class for Conversations. Each board might has many conversations and each conversation has many comments.
#
#
#
#


class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]
  before_filter :set_nav_identifier

  # GET /conversations/1
  def show
    @board = Board.find(params[:board_id])
    @comments = @conversation.comments
    @new_comment = Comment.new
    Notification.remove_notification current_user, @conversation
  end

  # GET /conversations/new
  def new
    @board = Board.find(params[:board_id])
    @conversation = Conversation.new
  end


  # POST /conversations
  def create
    @board = Board.find(params[:board_id])
    @conversation = @board.conversations.create(conversation_params)
    @conversation.user_id = current_user.id

    if @conversation.save
      redirect_to @board, notice: 'Conversation was successfully created.'
    else
      render action: 'new'
    end
  end

  # DELETE /conversations/1
  def destroy
    @board = Board.find(params[:board_id])
    @conversation.destroy
    redirect_to @board, notice: 'Conversation was successfully moderated.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_conversation
    @conversation = Conversation.find(params[:id])
  end

  def set_nav_identifier
    @current_nav_identifier = :boards
  end

  # Only allow a trusted parameter "white list" through.
  def conversation_params
    params.require(:conversation).permit(:title, :body, :board_id, :user_id)
  end
end

app/views/conversations/_comment_form.html.haml
.new_comment
  %i.h4.commenter= "Leave a comment"
  .loading= image_tag image_path("ajax-loader.gif"), alt: "Loading"

= simple_form_for([@board, @conversation, @new_comment],remote: true) do |f|
  .form-inputs
    = f.text_area :body, :rows => 3, :cols => 70, :placeholder => 'Enter your Comment here'
  %p
  .form-actions
    = f.submit "Add Comment", remote: true, :class => 'btn btn-primary'

app/views/conversations/_conversation.html.haml
.conversation
  =conversation.comments

app/views/conversations/_form.html.haml
= simple_form_for([@board, @conversation]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title

    = f.input :body, :label => "Initial Comment", :placeholder => 'Enter your Comment here', as: :text, :input_html => { :cols => 70, :rows => 3 }
    %br


  .form-actions
    = f.button :submit

app/views/conversations/ajax_get_comments.js.haml
//$("#{escape_javascript(render @conversation.comments)}").replaceWith("#comments");
//$(":input:not(input[type=submit])").val("");

app/views/conversations/edit.html.haml
%h1 Editing conversation
.div.tiles
  = render 'form'
.div.tile
  %p
    %br
    %br
    link_to 'Show', board_conversation_path(@board,@conversation)
    \|
    = link_to 'Back', @board

app/views/conversations/new.html.haml
%h1 New conversation

= render 'form'
%br
%br
= link_to 'Back', @board

app/views/conversations/show.html.haml
.page-header
  %h1= @conversation.title
%p
%h4 Initial comment
-if(@conversation.user.eql?(current_user))
  %i.commenter= "You"
-else
  %i.commenter= @conversation.user.firstname
.commenter.h6= @conversation.created_at.strftime("%B %d, %Y %I:%M%p")
.comment= @conversation.body

%hr

.col-md-8
  %h4 Replies
  .commentcount.h4=@conversation.comments.count

  -if(@comments)
    #comments= render @conversation.comments

  = render 'comment_form'
  .div.tiles
    %p
      %br
      %br
      %h3.i= link_to ' Back to the main board', board_path(@board), :class=> 'icon-circle-arrow-left'
      %br

-#
-#:javascript
-#  setInterval(function()
-#  {
-#      //$("#{escape_javascript(render @conversation.comments)}").appendTo("#comments");
-#      //$("#comments").load("#{escape_javascript(board_conversation_ajax_get_comments_path(@board,@conversation))}")
-#                 //alert("hi");
-#
-#  }, 3000);

:javascript
   $('.loading').hide();
   $(".btn").on("click", function() {
       $(document).ajaxStart(function() {

           $('.loading').show();
            $(".new_comment").fadeToggle(3000);

      });
      $(document).ajaxStop(function() {
           $('.loading').hide();
           $(".new_comment").fadeToggle(500);



    });
  });