config/routes.rb
Team10MiniProject::Application.routes.draw do

  root 'calendars#index'
  get "pages/awaiting", as: :awaiting
  get "pages/welcome", as: :welcome

  resources :boards  do
    resources :conversations do
      get :ajax_get_comments
      resources :comments
    end
  end

  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users do 
    member do
      get :report
    end
  end

  resources :shows

  resources :calendars

  resources :show_dates do
    member do
      get :show_foh
    end
    resources :fohs, only: [:new, :create]
  end

  resources :fohs, only: [:index]

  resources :trainings do
    member do
      get :attend
      get :attendee
    end
    collection do
      put :record_attendance

    end
    end

  resources :workshops do
    member do
      get :attend
      get :attendee
    end
    collection do
      put :record_attendance
    end
  end

  resources :show_roles do
    resources :role_applications, only: [:new, :create, :show]
  end
  resources :role_applications

  resources :socials


end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
end

app/controllers/calendars_controller.rb
#
#  Calenders_controller.rb
#


class CalendarsController < ApplicationController
  #before_action :set_calendar, only: [:show]
  before_filter :set_nav_identifier
  before_filter :authenticate_user!


  # GET /calendars
  def index
    @events = Workshop.all + Training.all + Social.all + ShowDate.all
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
  end


  private
  def set_nav_identifier
    @current_nav_identifier = :calendar
  end

end

app/views/calendars/index.html.haml
#calendar
  .container
    %br
    - if (current_user.role? "ProductionTeam")
      .buttonshow
        = link_to "Create New Show", new_show_path
    - if ((current_user.role? "TechManager") || (current_user.role? "SeniorCommittee"))
      .buttonworkshop
        = link_to "Create New Workshop", new_workshop_path
      .buttontraining
        = link_to "Create New Training", new_training_path
    - if ((current_user.role? "ProductionTeam") || (current_user.role? "SeniorCommittee")  || (current_user.role? "Committee"))
      .buttonsocial
        = link_to "Create New Social", new_social_path
      %br
      %br
      %br
      %br
      %br

    %h2

      %ularrow= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d")
      %mon= @date.strftime("%B %Y")
      %ularrow= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d")
    %h2
    = calendar_for @events, :year => @date.year, :month => @date.month do |calendar|
      = calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')
      - calendar.day(:day_method => :date) do |date, events|
        = date.day    
        %p

        - for event in events
          - if(event.event_name.eql?'ShowDate')
            .linkshow
              %a
                = link_to h(event .title), event
          - elsif(event.event_name.eql?"Social")
            .linksocial
              %a
                = link_to h(event .title), event
          - elsif(event.event_name.eql?"Training")
            .linktraining
              %a
                = link_to h(event .title), event
          - elsif(event.event_name.eql?"Workshop")
            .linkworkshop
              %a
                = link_to h(event .title), event
    %br