config/routes.rb
Team10MiniProject::Application.routes.draw do

  root 'calendars#index'
  get "pages/awaiting", as: :awaiting
  get "pages/welcome", as: :welcome

  resources :boards  do
    resources :conversations do
      get :ajax_get_comments
      resources :comments
    end
  end

  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users do 
    member do
      get :report
    end
  end

  resources :shows

  resources :calendars

  resources :show_dates do
    member do
      get :show_foh
    end
    resources :fohs, only: [:new, :create]
  end

  resources :fohs, only: [:index]

  resources :trainings do
    member do
      get :attend
      get :attendee
    end
    collection do
      put :record_attendance

    end
    end

  resources :workshops do
    member do
      get :attend
      get :attendee
    end
    collection do
      put :record_attendance
    end
  end

  resources :show_roles do
    resources :role_applications, only: [:new, :create, :show]
  end
  resources :role_applications

  resources :socials


end

app/models/show.rb
#
# show.rb
#
# Class to create a show. Each show has different show dates and show roles.
#

class Show < ActiveRecord::Base
  has_many :show_dates, :dependent => :destroy
  has_many :show_roles, :dependent => :destroy
  accepts_nested_attributes_for :show_dates, :allow_destroy => true
  accepts_nested_attributes_for :show_roles, :allow_destroy => true
  mount_uploader :image, ImageUploader # allow image upload
  validates :name, :director, :stage_manager, :producer, :synopsis, presence: true
  validate :show_dates_must_be_unique
  after_create :create_board
  has_one :board, :dependent => :destroy

  def create_board
    Board.create(:title => name, public: false, show_id: id)
  end

  # create shows with unique show dates
  def show_dates_must_be_unique
    errors.add(:show_dates, "can't be duplicated") unless show_dates.map(&:date).uniq.count == show_dates.to_a.count
  end

end

app/controllers/shows_controller.rb
#
# shows_controller.rb
#
# This is the controller class for Shows. Different users have different permissions to view, create, update and delete a show.
#
class ShowsController < ApplicationController
  # Load resources and set actions available
  load_and_authorize_resource
  before_action :set_show, only: [:show, :edit, :update, :destroy]
  before_filter :set_nav_identifier
  # GET all shows
  def index
    @shows = Show.all
  end

  # GET show by ID
  def show
    @board = Board.find_by_show_id(@show.id)
    @show_roles = ShowRole.select('id').where(show_id: @show.id)
    @user_ids = RoleApplication.where(show_role_id: @show_roles, status: 'Approved').pluck(:user_id)
  end

  # GET new shows
  def new
    @show = Show.new
    @show.show_dates.build
    @show.show_roles.build
  end

  # edit new shows
  def edit
  end

  # POST /shows
  def create
    @show = Show.new(show_params)

    # Check successful update
    if @show.save
      redirect_to @show, notice: 'Show was successfully created.'
    else
      render action: 'new'
    end
  end

  # Update show
  def update

    # Check for successful update
    if @show.update(show_params)
      # Find show by ID
      board = Board.find_by_show_id(@show.id)
      # Update params
      board.title= @show.name
      board.save
      redirect_to @show, notice: 'Show was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE show by ID
  def destroy
    @show.destroy
    redirect_to shows_url, notice: 'Show was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_show
    @show = Show.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def show_params
    params.require(:show).permit(:name, :image, :image_cache, :remove_image, :director, :stage_manager, :producer, :synopsis, show_dates_attributes: [:id, :title, :date, :time, :_destroy], show_roles_attributes: [:id, :position, :required_number, :_destroy])
  end

  def set_nav_identifier
    @current_nav_identifier = :shows
  end

end

app/helpers/shows_helper.rb
module ShowsHelper
  # this method is implemented to display the show name and three different icons for view, edit and delete buttons.
  def show_name_links(show)
    content_tag :h3 do
    # control the navigation links for different categories of users
    if (current_user.role? "ProductionTeam")
      [
        link_to_button('buttonshowname',show.name,show),
        link_to_button('buttonedit','Edit', edit_show_path(show)),
        link_to_button('buttondelete','Delete', show, {
          data: {confirm: 'Are you sure?'},
          method: :delete
      })
      ].join(' ').html_safe
    else
      [ link_to(show.name,show)
      ].join(' ').html_safe
    end
    end
  end

  # control the navigation links for different categories of users
  def show_navigation_links(show)
  content_tag :h3 do
    if (current_user.role? "ProductionTeam")
     [
      link_to('<i class="icon-circle-arrow-left"></i> Back'.html_safe,shows_path),
     "|",
      link_to('<i class="icon-edit-sign"></i> Edit'.html_safe,edit_show_path(show))  ,
      "|"                                                        ,
      link_to('<i class="icon-trash"></i> Delete'.html_safe,show, :method => :delete, :data => { :confirm => 'Are you sure?'})
    ].join(' ').html_safe
    else
      [link_to('<i class="icon-circle-arrow-left"></i> Back'.html_safe,shows_path)].join(' ').html_safe
    end
    end
  end
end

app/views/shows/_form.html.haml
// display errors, if any
- if @show.errors.any?
  -@show.errors.full_messages.each do |msg|
    %li=msg

// generate form 
= simple_form_for(@show) do |f|
  = f.error_notification
  %p
    // input required fields
    .form-inputs
      = f.input :name
      = image_tag @show.image_url, size: "140x140" if @show.image?
      = f.file_field :image
      - if @show.image?
        = f.label "Remove Avatar"
        = f.check_box :remove_image
        /Remove avatar
      = f.hidden_field :image_cache
      = f.input :director
      = f.input :stage_manager
      = f.input :producer
      = f.input :synopsis
      // allow multiple dates & roles to be inputted
      = f.fields_for :show_dates do |u|
        = render 'show_date_fields', :f => u
  %p
    = link_to_add_fields "Add Date", f, :show_dates

  %p
    .form-inputs
      = f.fields_for :show_roles do |u|
        = render 'show_role_fields', :f => u
  %p
    = link_to_add_fields "Add Role", f, :show_roles

  // submit form
  .form-actions
    = f.button :submit

app/views/shows/_show.html.haml
.show
  = show_name_links(show) # this method is defined in the shows_helper class to display the show name as well as related icons
  #show_image= image_tag show.image_url, alt: "No Poster", 	clip:rect("0px" "500px" "350px" "0px"); #width: 500, height: "auto"

app/views/shows/_show_date_fields.html.haml
// Show date fields to be inputted
%p.fields
  = f.label :title, "Date"
  = f.date_select :date,:value => Date.today
  = f.label :title, "Time"
  = f.time_select :time,:value => Time.now.strftime("%I:%M%p") 
  = link_to_remove_fields "remove", f

app/views/shows/_show_role_fields.html.haml
// Show role fields to be inputted
%p.fields

  = f.label :title, "Position"  
  // select role from list 
  = f.select :position ,options_for_select(["Lighting Operator", "Lighting Designer", "Sound Operator",
  "Sound Designer", "Assistant Stage Manager", "Deputy Stage Manager", "Set Designer",
  "Set Construction", "Costume Designer", "Costume Team", "Make up",
  "Make up team", "Producer", "Director", "Dialect Coach", "Physical Coach","Other"])
  // javascript used to display the 'Other' option
  :javascript
    $.fn.serializeObject = function()
    {
        var o = {};
        var a = this.serializeArray();
        $.each(a, function() {
            if (o[this.name]) {
                if (!o[this.name].push) {
                    o[this.name] = [o[this.name]];
                }
                o[this.name].push(this.value || '');
            } else {
                o[this.name] = this.value || '';
            }
        });
        return o;
    };
    var count = 0;
    $('select').each(function(i, select){

        if (!$(select).data('name')) {
            $(select).data('name', $(select).attr('name'));
        }
        $(select).change(function(){
            if (($(this).val() == 'other')) {
                $('<input/>', {
                    'name' : $(this).attr('name')
                }).insertAfter($(this));
                $(this).attr('name', '');
                throw BreakException;
            } else {
                $('input[name=\"'+$(this).data('name')+'\"]').remove();
                $(this).attr('name', $(this).data('name'));
            }
        });
    });  
  = f.label :title, "Required number"
  = f.number_field :required_number,:min => 1, :step => 1
  = link_to_remove_fields "remove", f

app/views/shows/edit.html.haml
// Edit show

%h1 Editing show
.div.tiles
  // display errors, if any
  - if @show.errors.any?
    -@show.errors.full_messages.each do |msg|
      %li=msg

  // display show fields in database
  = simple_form_for(@show) do |f|
    = f.error_notification
    %p
      .form-inputs
        = f.input :name
        = image_tag @show.image_url, size: "140x140" if @show.image?
        = f.file_field :image
        - if @show.image?
          = f.label "Remove Avatar"
          = f.check_box :remove_image
          /Remove avatar
        = f.hidden_field :image_cache
        = f.input :director
        = f.input :stage_manager
        = f.input :producer
        = f.label :synopsis
        %p= f.text_area :synopsis, :rows => 3, :cols => 70
        %p
        %b Show Date(s):
        = f.fields_for :show_dates do |u|
          = render 'show_date_fields', :f => u
        %p
          = link_to_add_fields "Add Date", f, :show_dates

    // display show roles, if any
    -if !@show.show_roles.empty?
      %b Show Role(s):
      %table.table.table-striped.table-bordered.table-responsive.table-nonfluid.table-hover
        -@show.show_roles.each do |c|
          -if(c.required_number)
            %tr
              %td= c.position
              %td= c.required_number
              %td= link_to 'Remove Role', [@box,c], :method => :delete, :data => { :confirm => 'Are you sure?' }
    %p
      .form-inputs
        %p.fields
          = link_to_add_fields "Add Role", f, :show_roles

    .form-actions
      = f.button :submit
.div.tiles
  %p
    %br
    %br
    = link_to 'Show', @show
    \|
    = link_to 'Back', shows_path

app/views/shows/index.html.haml
.page-header
  %h1 Shows

.dashboard
  .container
    // display links according to user permissions
    - if (current_user.role? "ProductionTeam")
      %a.buttonnewshow{href:new_show_path, role:"button"} Create New Show
      %br
      // display shows 
    - @shows.each do |show|
      = show_name_links(show) # this method is defined in the shows_helper class to display the show name as well as related icons

      .col-md-6
      %li.tile.tile-big.tile-4
        %figure
          .show
            #show_image= image_tag show.image_url, alt: "No Poster";
            //%img{src: show.image_url}
          %figcaption.tile-caption.caption-left #{show.synopsis}
          %figcaption.tile-caption.caption-right 
            Director: #{show.director}
            %br
            %br
            Show Date(s):
            %br
            -show.show_dates.each do |c|
              #{c.date.strftime("%B %d, %Y")}

app/views/shows/new.html.haml
%h1 New show
// display errors, if any
.div.tiles
  - if @show.errors.any?
    -@show.errors.full_messages.each do |msg|
      %li=msg

  // complete required fields
  = simple_form_for(@show) do |f|
    = f.error_notification
    %p
      .form-inputs
        = f.input :name
        = image_tag @show.image_url, size: "140x140" if @show.image?
        = f.file_field :image
        // allow image removing option
        - if @show.image?
          = f.label "Remove Avatar"
          = f.check_box :remove_image
        = f.hidden_field :image_cache
        = f.input :director
        = f.input :stage_manager
        = f.input :producer
        = f.label :synopsis
        %p= f.text_area :synopsis, :rows => 3, :cols => 70
        %p
        // allow more than one date and role
        = f.fields_for :show_dates do |u|
          = render 'show_date_fields', :f => u
    %p
      = link_to_add_fields "Add Date", f, :show_dates

    // allow multiple roles 
    %p
      .form-inputs
        = f.fields_for :show_roles do |u|
          = render 'show_role_fields', :f => u
    %p
      = link_to_add_fields "Add Role", f, :show_roles


    .form-actions
      = f.button :submit
.div.tiles
  %p
    %br
    %br
    = link_to 'Back', shows_path

app/views/shows/show.html.haml
// display link to message board if user has sufficient permissions
.page-header
  %h1= @show.name
  -if @user_ids.include? current_user.id
    -if(@board)
      %i=link_to 'Go to Message Board', board_path(@board)

%p
  // show details
  -if(@show.image?)
    = image_tag @show.image_url, alt: "No Poster", height: 480, width: "auto"
  -else
    %i= "No Show poster yet"
%p
  %b Director:
  = @show.director
%p
  %b Stage manager:
  = @show.stage_manager
%p
  %b Producer:
  = @show.producer
%p
  %b Synopsis:
  = @show.synopsis

%p
  // display all show dates
  -if !@show.show_dates.empty?
    %b Show Date(s):
    %table.table.table-striped.table-bordered.table-responsive.table-nonfluid.table-hover
      -@show.show_dates.each do |c|
        %tr
          %td= c.date.strftime("%B %d, %Y")
          %td= c.time.strftime("%I:%M%p")
          - if(c.foh_available)
            %td= link_to 'Apply for front of house', new_show_date_foh_path(c)
          -else
            %td= "Date is in the past"
          - if (current_user.role? "ProductionTeam")
            %td= link_to 'View filled positions', show_foh_show_date_path(c)
            %td= link_to 'Remove Date', [@box,c], :method => :delete, :data => { :confirm => 'Are you sure?' }
%p
%p
  // display all show roles
  -if !@show.show_roles.empty?
    %b Show Role(s):
    %table.table.table-striped.table-bordered.table-responsive.table-nonfluid.table-hover
      -@show.show_roles.each do |c|
        %tr
          - if(c.required_number > 0)
            %td= c.position
            %td= c.required_number
            -if(c.notexpired?)
              -if(c.applied?(current_user.id))
                %td= link_to 'View my application', current_user
              -else
                %td= link_to 'Apply for role', new_show_role_role_application_path(c)
            -if(current_user.role? "ProductionTeam")
              %td= link_to 'Remove Role', [@box,c], :method => :delete, :data => { :confirm => 'Are you sure?' }
            
%p
=show_navigation_links(@show)